-- Question bank expansion: Wisconsin Accident & Health (PSI Series 22-03)
-- Generated 2026-07-18. Topic authority: docs/wi-ah-outline.txt; Wisconsin facts
-- verified against docs/WI-OCI-STANDARDS.md. Schema matches the LIVE
-- public.questions table (domain/question/options jsonb/correct/explanation/
-- know_this/state_specific) — NOT the stale supabase/seed.sql.

-- Batch 1: wisconsin_health_regulation (1-20 of 32)
INSERT INTO public.questions (domain, difficulty, question, options, correct, explanation, know_this, state_specific) VALUES
('wisconsin_health_regulation', 'easy', 'Under Wisconsin law (s. 632.73), the right-to-return provision in an individual health insurance policy allows the policyowner to:', '["Exchange the policy for a group certificate","Return the policy within the specified period for a full refund of premium","Return the policy at any time for a prorated refund","Cancel the policy only if the insurer approves"]'::jsonb, 'Return the policy within the specified period for a full refund of premium', 'Wisconsin''s right-to-return (free look) statute lets a new policyowner examine the policy and return it within the statutory period for a full refund of all premium paid.', 'WI free look = return the policy, get a full refund.', 'Wisconsin'),
('wisconsin_health_regulation', 'medium', 'After an individual accident and health policy has been in force for two years, a Wisconsin insurer may generally contest the policy based on misstatements in the application only if:', '["The misstatement was unintentional","The premium is paid quarterly","The misstatement was fraudulent","The insured changes occupations"]'::jsonb, 'The misstatement was fraudulent', 'Wisconsin follows the standard two-year structure for the insurer''s right to contest: after two years, only fraudulent misstatements can be used to void coverage or deny a claim.', 'After 2 years, only fraud can unwind an A&H policy.', 'Wisconsin'),
('wisconsin_health_regulation', 'medium', 'Wisconsin s. 632.746 addresses preexisting conditions in group health coverage primarily by:', '["Requiring all preexisting conditions to be permanently excluded","Allowing insurers to cancel coverage when a preexisting condition is discovered","Requiring insureds to pay a surcharge for preexisting conditions","Limiting how insurers may apply preexisting condition exclusions"]'::jsonb, 'Limiting how insurers may apply preexisting condition exclusions', 'The statute restricts, rather than expands, insurers'' ability to impose preexisting condition exclusions on group coverage, limiting how such exclusions may be applied.', 's. 632.746 limits preexisting exclusions — it never expands them.', 'Wisconsin'),
('wisconsin_health_regulation', 'easy', 'Wisconsin''s grace period requirement for health insurance policies (s. 632.78) ensures that:', '["Coverage remains in force for a period after a premium due date even though the premium is unpaid","The insurer must waive one premium payment per year","Claims incurred during the grace period are automatically denied","The policy may be reinstated at any time without proof of insurability"]'::jsonb, 'Coverage remains in force for a period after a premium due date even though the premium is unpaid', 'A grace period keeps the policy in force for a limited time after the premium due date, so a slightly late payment does not cause a lapse in coverage.', 'Grace period = late premium, coverage still on.', 'Wisconsin'),
('wisconsin_health_regulation', 'medium', 'To exercise Wisconsin group health continuation rights under s. 632.897, an employee losing group eligibility generally must:', '["Provide evidence of insurability to the insurer","Elect continuation and pay the required premium within the statutory timeframe","Convert immediately to a Medicare supplement policy","Obtain written approval from the employer''s board"]'::jsonb, 'Elect continuation and pay the required premium within the statutory timeframe', 'Wisconsin continuation is exercised by timely election and premium payment; the insurer may not require proof of insurability to continue group coverage.', 'WI continuation: elect and pay — no health questions.', 'Wisconsin'),
('wisconsin_health_regulation', 'medium', 'Under Wisconsin law, when a marriage ends in divorce or annulment, the former spouse of a covered group member generally has the right to:', '["Continue group health coverage or convert to individual coverage","Remain covered only until the end of the policy month","Keep coverage only if the employer consents","Purchase coverage only through the federal exchange"]'::jsonb, 'Continue group health coverage or convert to individual coverage', 'Section 632.897(4) protects a former spouse by providing continuation and conversion rights when coverage would otherwise end because of divorce or annulment.', 'Divorce does not end WI health coverage — continuation and conversion rights apply.', 'Wisconsin'),
('wisconsin_health_regulation', 'medium', 'Wisconsin''s independent review process (s. 632.835) is designed to resolve disputes in which an insurer has denied coverage primarily on the basis of:', '["Nonpayment of premium","Producer licensing violations","Medical necessity or the experimental nature of treatment","Errors in premium billing"]'::jsonb, 'Medical necessity or the experimental nature of treatment', 'Independent review gives insureds an external appeal when an insurer denies a claim as not medically necessary or as experimental treatment.', 'Independent review = medical necessity and experimental treatment disputes.', 'Wisconsin'),
('wisconsin_health_regulation', 'easy', 'Under Wisconsin''s independent review law, a disputed adverse benefit determination is reviewed by:', '["The insurer''s own claims committee","The policyholder''s employer","The producer who sold the policy","An independent review organization outside the insurer"]'::jsonb, 'An independent review organization outside the insurer', 'The review is conducted by an independent review organization that is not affiliated with the insurer, giving the insured an impartial second look at the denial.', 'Independent review happens outside the insurer — that is the whole point.', 'Wisconsin'),
('wisconsin_health_regulation', 'easy', 'Wisconsin requires health insurers to maintain an internal grievance procedure primarily so that insureds can:', '["Have coverage complaints and claim denials formally reviewed by the insurer","Sue the insurer without going to court","Change their producer of record","Obtain premium refunds automatically"]'::jsonb, 'Have coverage complaints and claim denials formally reviewed by the insurer', 'The grievance procedure is the insurer''s formal internal process for reviewing complaints and adverse determinations before external remedies such as independent review.', 'Grievance first (internal), independent review after (external).', 'Wisconsin'),
('wisconsin_health_regulation', 'easy', 'A step therapy protocol used by a health insurer requires that an insured:', '["Complete a physical exam before each refill","Try a lower-cost drug or treatment before the plan covers the originally prescribed one","Use mail-order pharmacies exclusively","Pay full cost for all brand-name drugs"]'::jsonb, 'Try a lower-cost drug or treatment before the plan covers the originally prescribed one', 'Step therapy (fail-first) protocols require the insured to try preferred, typically lower-cost therapies before the plan will cover the prescribed alternative.', 'Step therapy = fail first, then step up.', 'Wisconsin'),
('wisconsin_health_regulation', 'medium', 'Wisconsin''s step therapy statute (s. 632.866) protects patients by requiring insurers that use step therapy protocols to:', '["Eliminate step therapy for all generic drugs","Cover all prescription drugs without prior authorization","Apply step therapy only to insureds over age 65","Provide a clear process to request an exception when the protocol is medically inappropriate"]'::jsonb, 'Provide a clear process to request an exception when the protocol is medically inappropriate', 'The statute requires a transparent exception process so a patient can bypass the protocol when it is medically inappropriate for their condition.', 'WI step therapy law = an exception process is required.', 'Wisconsin'),
('wisconsin_health_regulation', 'medium', 'Under Wisconsin''s health insurance marketing rules, before recommending an individual health policy a producer should have reasonable grounds to believe the policy is:', '["Not unsuitable given the applicant''s existing coverage and insurance needs","The lowest-priced policy available in the market","Issued by a mutual insurer","Identical to the applicant''s prior coverage"]'::jsonb, 'Not unsuitable given the applicant''s existing coverage and insurance needs', 'Wisconsin''s suitability standard (s. Ins 3.27(7)) requires the recommendation to fit the applicant''s circumstances, considering existing coverage and needs.', 'Suitability: match the policy to the person, not the commission.', 'Wisconsin'),
('wisconsin_health_regulation', 'medium', 'Under Wisconsin''s accident and health advertising rule (Ins 3.27), an advertisement that describes a limited accident-only policy as providing comprehensive health protection is best described as:', '["Acceptable if a disclaimer appears in the policy","Permitted for direct-mail solicitations only","Deceptive advertising prohibited by the rule","Legal as long as the insurer is licensed in Wisconsin"]'::jsonb, 'Deceptive advertising prohibited by the rule', 'Advertising may not misrepresent the scope of coverage; portraying a limited policy as comprehensive is deceptive and violates the advertising rule.', 'Ads cannot make limited coverage sound comprehensive.', 'Wisconsin'),
('wisconsin_health_regulation', 'easy', 'Under Wisconsin''s mandated benefits law, a health insurance policy covering dependents must cover a newborn child of the insured:', '["Beginning 31 days after birth","Only after the child receives a physical examination","Only if the mother was hospitalized during delivery","From the moment of birth, including coverage for congenital defects"]'::jsonb, 'From the moment of birth, including coverage for congenital defects', 'Section 632.895(5) requires coverage of newborns from the moment of birth, including treatment of congenital defects and birth abnormalities.', 'Newborns are covered from the moment of birth.', 'Wisconsin'),
('wisconsin_health_regulation', 'medium', 'Under Wisconsin law (s. 632.896), a child placed for adoption with an insured must be covered under the insured''s health policy:', '["Only after the adoption is finalized in court","On the same basis as other dependent children","After a six-month waiting period","Only if the child passes medical underwriting"]'::jsonb, 'On the same basis as other dependent children', 'Adopted children and children placed for adoption must be covered on the same terms as other dependents, without underwriting or waiting periods tied to the adoption.', 'Adopted kids get the same coverage as birth kids, from placement.', 'Wisconsin'),
('wisconsin_health_regulation', 'hard', 'Wisconsin''s mandated benefits are unusual among states in that health policies covering dependents must also extend coverage to:', '["All grandchildren living in the state","Nieces and nephews of the insured","Newborn grandchildren, when the child''s parent is a covered dependent","Foster children over age 18"]'::jsonb, 'Newborn grandchildren, when the child''s parent is a covered dependent', 'Section 632.895(5m) extends mandated coverage to the newborn child of a covered dependent child — the insured''s grandchild — in specified circumstances.', 'The WI mandate list reaches grandchildren — s. 632.895(5m).', 'Wisconsin'),
('wisconsin_health_regulation', 'medium', 'Under Wisconsin law, a dependent child who reaches the policy''s limiting age may remain covered under a parent''s health policy if the child is:', '["Enrolled in any postsecondary school","Employed part-time","Living within 50 miles of the insured","Incapable of self-support because of a disability and dependent on the insured"]'::jsonb, 'Incapable of self-support because of a disability and dependent on the insured', 'Section 632.88 requires continued coverage past the limiting age for children who cannot support themselves due to disability and who remain dependent on the insured.', 'Disabled dependents do not age off — s. 632.88.', 'Wisconsin'),
('wisconsin_health_regulation', 'easy', 'Wisconsin''s mandated benefits law requires health insurance policies to provide coverage for which cancer screening for women?', '["Mammograms","Full-body MRI scans","Annual genetic testing","Bone density scans"]'::jsonb, 'Mammograms', 'Mammography screening is on Wisconsin''s mandated benefits list under s. 632.895(8).', 'Mammography screening is a WI mandate — s. 632.895(8).', 'Wisconsin'),
('wisconsin_health_regulation', 'medium', 'Wisconsin''s diabetes mandate (s. 632.895(6)) requires health policies that cover diabetes to include coverage for:', '["Only insulin administered in a hospital","Diabetes equipment, supplies, and self-management education","Weight-loss surgery for all diabetics","Experimental gene therapy"]'::jsonb, 'Diabetes equipment, supplies, and self-management education', 'The diabetes mandate covers the equipment, supplies, and self-management training needed to manage the disease, not just drugs given in a facility.', 'WI diabetes mandate = equipment, supplies, and education.', 'Wisconsin'),
('wisconsin_health_regulation', 'medium', 'Which condition is subject to a specific Wisconsin mandated-benefit statute requiring coverage of its treatment, including dialysis?', '["Seasonal allergies","Carpal tunnel syndrome","Kidney disease","Migraine headaches"]'::jsonb, 'Kidney disease', 'Section 632.895(4) mandates coverage for treatment of kidney disease, including dialysis, in policies subject to the mandate.', 'Kidney disease (including dialysis) is a WI mandate — s. 632.895(4).', 'Wisconsin');

-- Batch 2: wisconsin_health_regulation (21-32 of 32) + medicare (1-8 of 17)
INSERT INTO public.questions (domain, difficulty, question, options, correct, explanation, know_this, state_specific) VALUES
('wisconsin_health_regulation', 'medium', 'Under Wisconsin''s autism mandate (s. 632.895(12m)), health insurance policies must provide coverage for:', '["Autism screening only, with all treatment excluded","Treatment of autism spectrum disorders, including intensive-level and nonintensive-level services","Autism services only for children under age 2","Residential placement in any facility the family chooses"]'::jsonb, 'Treatment of autism spectrum disorders, including intensive-level and nonintensive-level services', 'Wisconsin mandates coverage of evidence-based treatment for autism spectrum disorders at both intensive and nonintensive levels of service.', 'Autism treatment — intensive and nonintensive — is mandated in WI.', 'Wisconsin'),
('wisconsin_health_regulation', 'easy', 'Under Wisconsin law, a health insurance policy that covers mastectomy must also cover:', '["Breast reconstruction of the affected tissue","Cosmetic surgery unrelated to the mastectomy","Annual spa therapy","Private-duty nursing for one year"]'::jsonb, 'Breast reconstruction of the affected tissue', 'Section 632.895(13) requires policies covering mastectomy to also cover breast reconstruction of the affected tissue.', 'Cover the mastectomy, cover the reconstruction — s. 632.895(13).', 'Wisconsin'),
('wisconsin_health_regulation', 'medium', 'Wisconsin''s mandated benefits law requires coverage of hearing aids and cochlear implants for which group of insureds?', '["Adults over age 65 only","All insureds regardless of age","Infants and children","Only insureds in high-noise occupations"]'::jsonb, 'Infants and children', 'Section 632.895(16) mandates coverage of hearing aids, cochlear implants, and related treatment for infants and children.', 'Hearing aids and cochlear implants: mandated for kids — s. 632.895(16).', 'Wisconsin'),
('wisconsin_health_regulation', 'medium', 'Wisconsin s. 632.89 requires group health policies to provide coverage related to which of the following?', '["Cosmetic surgery","Vision correction surgery","Long-term custodial care","Nervous and mental disorders and alcohol or drug abuse"]'::jsonb, 'Nervous and mental disorders and alcohol or drug abuse', 'Section 632.89 is Wisconsin''s mental health and substance abuse coverage statute for group health policies.', 's. 632.89 = mental health and substance abuse coverage in group plans.', 'Wisconsin'),
('wisconsin_health_regulation', 'medium', 'Under Wisconsin''s chiropractic statute (s. 632.87), if a health policy covers the diagnosis or treatment of a condition, the insurer may not deny coverage solely because the service was provided by:', '["A licensed chiropractor acting within the scope of the chiropractor''s license","An out-of-state hospital","A physician assistant","A registered pharmacist"]'::jsonb, 'A licensed chiropractor acting within the scope of the chiropractor''s license', 'Wisconsin law prohibits denying coverage for an otherwise covered service solely because it was performed by a chiropractor acting within the scope of licensure.', 'Covered condition + licensed chiropractor = coverage cannot be denied.', 'Wisconsin'),
('wisconsin_health_regulation', 'hard', 'Wisconsin''s home care mandate (s. 632.895(2)) generally requires certain health policies that cover hospital or medical expenses to also cover:', '["Housekeeping services for all policyholders","Home care services as an alternative to hospitalization or institutional care","Home security systems for disabled insureds","Room and board at any assisted living facility"]'::jsonb, 'Home care services as an alternative to hospitalization or institutional care', 'The home care mandate ensures insureds can receive covered care at home in place of more costly hospital or institutional confinement.', 'WI mandates home care as an alternative to the hospital.', 'Wisconsin'),
('wisconsin_health_regulation', 'medium', 'Which of the following is on Wisconsin''s list of mandated health insurance benefits under s. 632.895?', '["Cosmetic dentistry","Concierge medicine retainer fees","Skilled nursing care in a skilled nursing facility","Health club memberships"]'::jsonb, 'Skilled nursing care in a skilled nursing facility', 'Section 632.895(3) mandates coverage of skilled nursing care in a skilled nursing facility for policies subject to the mandate.', 'Skilled nursing facility care is a WI mandated benefit.', 'Wisconsin'),
('wisconsin_health_regulation', 'hard', 'Under Wisconsin''s maternity mandate (s. 632.895(7)), if a health insurance policy provides maternity benefits, those benefits must be provided for:', '["The named insured and spouse only","Employees but not dependents","Only insureds over age 21","All persons covered under the policy, including dependent children"]'::jsonb, 'All persons covered under the policy, including dependent children', 'When maternity coverage is included, Wisconsin requires it to extend to every covered person, including covered dependent children.', 'Maternity coverage extends to covered dependents too — s. 632.895(7).', 'Wisconsin'),
('wisconsin_health_regulation', 'medium', 'Under Wisconsin law (s. 632.895(17)), a health insurance policy that covers outpatient prescription drugs must also cover:', '["Over-the-counter vitamins","Homeopathic remedies","Contraceptives prescribed by a health care provider","Cosmetic dermatology drugs"]'::jsonb, 'Contraceptives prescribed by a health care provider', 'Policies covering outpatient prescription drugs must include coverage for prescribed contraceptives and related outpatient services.', 'Rx coverage in WI must include prescribed contraceptives.', 'Wisconsin'),
('wisconsin_health_regulation', 'medium', 'Wisconsin''s cancer clinical trials mandate prevents insurers from doing which of the following?', '["Denying coverage of routine care because the insured is participating in a cancer clinical trial","Refusing to pay for the investigational drug being studied in a trial","Charging copayments for oncology visits","Requiring preauthorization for chemotherapy"]'::jsonb, 'Denying coverage of routine care because the insured is participating in a cancer clinical trial', 'The mandate protects routine patient care costs during trial participation; the investigational item itself is typically funded by the trial sponsor.', 'Trial participation cannot cost you routine care coverage.', 'Wisconsin'),
('wisconsin_health_regulation', 'medium', 'Under Wisconsin''s oral chemotherapy parity law (s. 632.867), insurers that cover chemotherapy must:', '["Cover oral chemotherapy only after intravenous options fail","Limit oral chemotherapy to generic drugs","Apply a separate deductible to oral chemotherapy","Cover orally administered chemotherapy on a basis no less favorable than injected or intravenous chemotherapy"]'::jsonb, 'Cover orally administered chemotherapy on a basis no less favorable than injected or intravenous chemotherapy', 'The parity law prohibits treating oral chemotherapy less favorably than chemotherapy administered by injection or IV.', 'Chemo parity: pills treated no worse than IV.', 'Wisconsin'),
('wisconsin_health_regulation', 'hard', 'Wisconsin''s prescription eye drop mandate (s. 632.895(16t)) requires health policies that cover prescription eye drops to also cover:', '["Designer eyewear","Early refills of the eye drops under specified conditions","Laser vision correction surgery","Contact lens insurance"]'::jsonb, 'Early refills of the eye drops under specified conditions', 'The mandate requires coverage of early refills of prescription eye drops under the conditions specified in the statute.', 'The eye drop mandate = early refills covered.', 'Wisconsin'),
('medicare', 'easy', 'Medicare Part A (Hospital Insurance) is financed primarily through:', '["Monthly premiums paid by all beneficiaries","Payroll taxes paid by workers and employers","State income taxes","Beneficiary copayments"]'::jsonb, 'Payroll taxes paid by workers and employers', 'Part A is funded mainly by the Medicare payroll tax, which is why most beneficiaries receive it premium-free.', 'Part A = payroll-tax funded, usually premium-free.', NULL),
('medicare', 'medium', 'Most individuals qualify for premium-free Medicare Part A at age 65 because they or a spouse:', '["Paid Medicare payroll taxes for the required number of working quarters","Purchased a Medicare supplement policy","Enrolled in Medicaid","Served in the military"]'::jsonb, 'Paid Medicare payroll taxes for the required number of working quarters', 'Premium-free Part A is earned through sufficient quarters of Medicare-covered employment (generally 40 quarters, about 10 years) by the individual or spouse.', 'Work about 40 quarters and Part A is premium-free.', NULL),
('medicare', 'hard', 'Under Medicare Part A, a benefit period begins upon inpatient admission and ends when the beneficiary:', '["Is discharged from the hospital","Reaches age 70","Has been out of the hospital or skilled nursing facility for 60 consecutive days","Exhausts a calendar-year deductible"]'::jsonb, 'Has been out of the hospital or skilled nursing facility for 60 consecutive days', 'Part A measures benefits by benefit periods, not calendar years; a period ends only after 60 consecutive days without inpatient or skilled nursing care.', 'A Part A benefit period ends 60 days after care ends — not at discharge.', NULL),
('medicare', 'easy', 'Medicare Part B primarily covers:', '["Inpatient hospital room and board","Physician services and outpatient care","Long-term custodial nursing home care","Prescription drugs taken at home"]'::jsonb, 'Physician services and outpatient care', 'Part B is Medical Insurance, covering doctors'' services, outpatient care, diagnostic tests, and durable medical equipment.', 'Part B = doctors and outpatient services.', NULL),
('medicare', 'medium', 'Medicare Part B is funded through a combination of:', '["Payroll taxes only","State matching funds","Employer contributions only","Beneficiary premiums and federal general revenues"]'::jsonb, 'Beneficiary premiums and federal general revenues', 'Unlike Part A, Part B is voluntary and financed by monthly beneficiary premiums plus general revenues of the federal government.', 'Part B: premiums + general tax revenues.', NULL),
('medicare', 'medium', 'An individual''s initial enrollment period for Medicare Part B is the seven-month window that:', '["Begins three months before the month of the 65th birthday and ends three months after it","Begins on January 1 of the year the individual turns 65","Runs from the birthday through the end of the year","Opens only after the individual retires"]'::jsonb, 'Begins three months before the month of the 65th birthday and ends three months after it', 'The initial enrollment period spans seven months: the three months before, the month of, and the three months after the 65th birthday month.', 'IEP = 3 months before + birthday month + 3 months after.', NULL),
('medicare', 'hard', 'A person who fails to enroll in Medicare Part B during the initial enrollment period may sign up later during the general enrollment period, but may face:', '["A permanently increased Part B premium as a late enrollment penalty","Loss of Part A coverage","A five-year waiting period","Mandatory medical underwriting"]'::jsonb, 'A permanently increased Part B premium as a late enrollment penalty', 'Late Part B enrollment without qualifying coverage triggers a premium penalty that generally lasts for as long as the person keeps Part B.', 'Skip Part B enrollment, pay a lifetime penalty.', NULL);

-- Batch 3: medicare (9-17 of 17) + medicaid (1-8 of 8) + ltc (1-3 of 18)
INSERT INTO public.questions (domain, difficulty, question, options, correct, explanation, know_this, state_specific) VALUES
('medicare', 'medium', 'Which of the following is generally excluded from Medicare Part B coverage?', '["Routine dental care and dentures","Doctor office visits","Outpatient diagnostic tests","Durable medical equipment"]'::jsonb, 'Routine dental care and dentures', 'Original Medicare excludes routine dental care, hearing aids, and eyeglasses; office visits, diagnostics, and durable medical equipment are Part B benefits.', 'Medicare skips routine dental, hearing aids, and eyeglasses.', NULL),
('medicare', 'medium', 'A Medicare beneficiary who goes without Part D or other creditable prescription drug coverage for an extended period may face:', '["Cancellation of Part A","A late enrollment penalty added to the Part D premium","Exclusion from Medicare Advantage plans","Mandatory Medigap enrollment"]'::jsonb, 'A late enrollment penalty added to the Part D premium', 'Going without creditable drug coverage for an extended period results in a permanent late enrollment penalty added to the Part D premium.', 'No creditable drug coverage now = Part D penalty later.', NULL),
('medicare', 'easy', 'Medicare Part D prescription drug plans are offered by:', '["The federal government directly","State insurance departments","Private insurance companies approved by Medicare","Hospitals"]'::jsonb, 'Private insurance companies approved by Medicare', 'Part D coverage is delivered through private stand-alone drug plans or Medicare Advantage drug plans approved by Medicare.', 'Part D is Medicare-approved but privately run.', NULL),
('medicare', 'medium', 'To enroll in a Medicare Advantage (Part C) plan, an individual generally must:', '["Drop Medicare Part A","Purchase a Medigap policy first","Be under age 65","Be enrolled in both Medicare Parts A and B"]'::jsonb, 'Be enrolled in both Medicare Parts A and B', 'Medicare Advantage replaces Original Medicare delivery but requires enrollment in Parts A and B, and the member continues paying the Part B premium.', 'Part C requires A + B — and you keep paying the Part B premium.', NULL),
('medicare', 'easy', 'The primary purpose of a Medicare supplement (Medigap) policy is to:', '["Pay deductibles, coinsurance, and other cost-sharing amounts not paid by Medicare","Replace Medicare as the primary payer","Provide long-term custodial care benefits","Add dental and vision coverage to Medicare"]'::jsonb, 'Pay deductibles, coinsurance, and other cost-sharing amounts not paid by Medicare', 'Medigap policies fill the gaps in Original Medicare by covering cost-sharing amounts such as deductibles and coinsurance; Medicare remains the primary payer.', 'Medigap fills Medicare''s cost-sharing gaps.', NULL),
('medicare', 'medium', 'An individual''s Medigap open enrollment period generally lasts how long after enrolling in Part B at age 65 or older?', '["30 days","6 months","12 months","3 years"]'::jsonb, '6 months', 'The Medigap open enrollment period runs six months from Part B enrollment at 65 or older, during which the applicant cannot be denied or rated up for health.', 'Medigap open enrollment = 6 months, no medical underwriting.', NULL),
('medicare', 'medium', 'Medicare supplement policies must generally be:', '["Guaranteed renewable","Cancelable at the insurer''s option","Renewed only with evidence of insurability","Nonrenewable after age 80"]'::jsonb, 'Guaranteed renewable', 'Medigap policies are guaranteed renewable; the insurer may cancel only for nonpayment of premium or material misrepresentation.', 'Medigap = guaranteed renewable.', NULL),
('medicare', 'medium', 'When selling a Medicare supplement policy, a producer must generally provide the applicant with:', '["A copy of the insurer''s annual report","The applicant''s Medicare claim history","A notarized suitability affidavit","An outline of coverage and the Guide to Health Insurance for People with Medicare"]'::jsonb, 'An outline of coverage and the Guide to Health Insurance for People with Medicare', 'Medigap marketing standards require delivery of an outline of coverage and the government buyer''s guide so applicants can compare and avoid duplicate coverage.', 'Medigap sale = outline of coverage + the Medicare buyer''s guide.', NULL),
('medicare', 'hard', 'For individuals who first become eligible for Medicare on or after January 1, 2020, Medicare supplement plans sold to them may no longer cover:', '["The Medicare Part B deductible","The Part A hospital deductible","Foreign travel emergency care","Part A coinsurance amounts"]'::jsonb, 'The Medicare Part B deductible', 'Under MACRA, plans covering the Part B deductible closed to newly eligible beneficiaries, which is why plans like C and F are unavailable to that group.', 'Newly eligible in 2020+ cannot buy Medigap that pays the Part B deductible.', NULL),
('medicaid', 'easy', 'Medicaid is administered by:', '["The federal government exclusively","Individual states, within federal guidelines","Private insurers under contract with the Social Security Administration","County hospitals"]'::jsonb, 'Individual states, within federal guidelines', 'Medicaid is a joint federal-state program: the federal government sets broad requirements and shares funding, while each state administers its own program.', 'Medicaid = state-run, federally guided.', NULL),
('medicaid', 'medium', 'Which program is the largest public payer of long-term nursing home care for individuals who meet income and asset limits?', '["Medicaid","Medicare Part A","Medicare Part C","TRICARE"]'::jsonb, 'Medicaid', 'Medicare covers only limited skilled care, so Medicaid is the primary public payer of extended nursing home care for those who qualify financially.', 'Long nursing home stays = Medicaid, not Medicare.', NULL),
('medicaid', 'hard', 'An individual whose income is too high for Medicaid may still qualify in some cases by spending down, which means:', '["Incurring medical expenses that reduce countable income to the eligibility level","Transferring all assets to a spouse in the same month","Purchasing an annuity from the state","Enrolling in Medicare Part D"]'::jsonb, 'Incurring medical expenses that reduce countable income to the eligibility level', 'Under spend-down (medically needy) provisions, incurred medical expenses are subtracted from income, allowing eligibility once the excess is offset.', 'Spend-down: medical bills eat income until Medicaid kicks in.', NULL),
('medicaid', 'medium', 'Compared with Medicare, Medicaid coverage is broader in that Medicaid may pay for:', '["Custodial long-term care services","Inpatient hospital care","Physician services","Outpatient surgery"]'::jsonb, 'Custodial long-term care services', 'Both programs cover hospital and physician services, but only Medicaid routinely covers custodial long-term care for eligible individuals.', 'Custodial care: Medicaid yes, Medicare no.', NULL),
('medicaid', 'medium', 'For a beneficiary enrolled in both Medicare and Medicaid, claims are generally paid in which order?', '["Medicaid pays first and Medicare pays the balance","Both programs split each claim equally","Medicare pays first and Medicaid pays last","The beneficiary chooses which program pays first"]'::jsonb, 'Medicare pays first and Medicaid pays last', 'For dual eligibles, Medicare is the primary payer and Medicaid pays remaining covered amounts as the payer of last resort.', 'Duals: Medicare first, Medicaid last.', NULL),
('medicaid', 'hard', 'Medicaid is described as the payer of last resort, meaning:', '["All other available coverage sources must pay before Medicaid pays","Medicaid covers only emergency services","Providers must bill patients before billing Medicaid","Medicaid benefits end after one year"]'::jsonb, 'All other available coverage sources must pay before Medicaid pays', 'If a Medicaid recipient has any other coverage — Medicare, group insurance, or liability coverage — those sources pay first and Medicaid pays last.', 'Medicaid pays last — after every other payer.', NULL),
('medicaid', 'medium', 'Which benefit must state Medicaid programs cover under federal requirements?', '["Inpatient hospital services","Cosmetic surgery","Adult dental implants","Health club memberships"]'::jsonb, 'Inpatient hospital services', 'Federal law requires state Medicaid programs to cover core services such as inpatient and outpatient hospital care, physician services, and nursing facility care.', 'States must cover core services like inpatient hospital care.', NULL),
('medicaid', 'medium', 'Which statement best describes the help available to certain low-income Medicare beneficiaries through Medicaid?', '["Medicaid may pay their Medicare premiums, deductibles, and coinsurance","Medicaid replaces their Medicare coverage entirely","Medicaid refunds their Medicare payroll taxes","Medicaid provides them a free private Medigap policy"]'::jsonb, 'Medicaid may pay their Medicare premiums, deductibles, and coinsurance', 'Through Medicaid, qualifying low-income Medicare beneficiaries can get help with Medicare premiums and cost-sharing amounts.', 'Medicaid can pick up Medicare''s premiums and cost-sharing for the low-income.', NULL),
('ltc', 'easy', 'Which level of long-term care involves round-the-clock care ordered by a physician and performed by skilled medical personnel?', '["Custodial care","Skilled nursing care","Respite care","Adult day care"]'::jsonb, 'Skilled nursing care', 'Skilled care is continuous, physician-ordered care delivered by skilled medical professionals such as registered nurses.', 'Skilled care = 24/7, doctor-ordered, nurse-delivered.', NULL),
('ltc', 'medium', 'Intermediate care differs from skilled nursing care in that intermediate care:', '["Is provided intermittently rather than around the clock","Requires no physician involvement","Is always provided at home","Covers only mental health conditions"]'::jsonb, 'Is provided intermittently rather than around the clock', 'Intermediate care is occasional or intermittent nursing and rehabilitative care, still ordered by a physician but not required continuously.', 'Intermediate = skilled help, but only occasionally.', NULL),
('ltc', 'easy', 'Home health care, as a long-term care benefit, is best described as:', '["Care provided in the insured''s residence, such as skilled nursing visits or therapy","Room and board in a nursing facility","Emergency ambulance transport","Inpatient hospice care only"]'::jsonb, 'Care provided in the insured''s residence, such as skilled nursing visits or therapy', 'Home health care delivers covered services — nursing visits, therapy, home health aide services — in the insured''s own home.', 'Home health care = care where you live.', NULL);

-- Batch 4: ltc (4-18 of 18) + group_health (1-5 of 17)
INSERT INTO public.questions (domain, difficulty, question, options, correct, explanation, know_this, state_specific) VALUES
('ltc', 'easy', 'Selecting a longer benefit period on a long-term care policy will generally:', '["Decrease the premium","Increase the premium","Have no effect on the premium","Eliminate the elimination period"]'::jsonb, 'Increase the premium', 'A longer benefit period obligates the insurer to pay benefits for more time, so the premium is higher.', 'More benefit years = more premium.', NULL),
('ltc', 'medium', 'The elimination period in a long-term care policy functions most like:', '["A coinsurance percentage","A benefit maximum","A deductible expressed in days rather than dollars","A grace period"]'::jsonb, 'A deductible expressed in days rather than dollars', 'The insured pays for care during the elimination period before policy benefits begin, making it a time-based deductible.', 'The LTC elimination period is a deductible measured in days.', NULL),
('ltc', 'medium', 'A long-term care policy that pays a fixed daily amount regardless of actual expenses incurred uses which benefit approach?', '["Reimbursement","Indemnity (per diem)","Capitation","Coordination of benefits"]'::jsonb, 'Indemnity (per diem)', 'Per diem (indemnity) policies pay the stated daily amount once the insured qualifies, regardless of actual charges; reimbursement policies pay actual expenses up to a cap.', 'Per diem pays the flat daily amount — receipts not required.', NULL),
('ltc', 'medium', 'The guarantee of insurability option on a long-term care policy allows the insured to:', '["Purchase additional coverage later without evidence of insurability","Convert the policy to life insurance","Freeze premiums for life","Transfer the policy to a spouse"]'::jsonb, 'Purchase additional coverage later without evidence of insurability', 'This optional benefit lets the insured increase coverage at specified intervals without new medical underwriting.', 'Guarantee of insurability = buy more later, no health questions.', NULL),
('ltc', 'medium', 'A return-of-premium rider on a long-term care policy generally provides that:', '["Some or all premiums are returned if the insured dies or surrenders after using few or no benefits","Premiums are refunded every five years automatically","The insurer waives premiums during a claim","Benefits double after ten years"]'::jsonb, 'Some or all premiums are returned if the insured dies or surrenders after using few or no benefits', 'The rider returns a portion of premiums paid, typically reduced by any benefits received, upon death or surrender.', 'Return-of-premium rider: unused premiums can come back.', NULL),
('ltc', 'hard', 'To receive benefits from a tax-qualified long-term care policy, the insured must be certified as chronically ill, with the condition expected to last at least:', '["30 days","6 months","90 days","2 years"]'::jsonb, '90 days', 'Tax-qualified policies require certification by a licensed health care practitioner that the insured is chronically ill and expected to need care for at least 90 days.', 'Tax-qualified LTC: chronically ill + 90-day certification.', NULL),
('ltc', 'medium', 'The key advantage of buying a Long-Term Care Partnership policy is that the insured may:', '["Qualify for Medicaid while protecting assets equal to the benefits the policy paid","Deduct all premiums from federal income tax without limit","Receive benefits without any elimination period","Transfer the policy to their children"]'::jsonb, 'Qualify for Medicaid while protecting assets equal to the benefits the policy paid', 'Partnership policies provide dollar-for-dollar asset disregard: assets equal to benefits paid are protected when determining Medicaid eligibility.', 'Partnership policy: every benefit dollar shields an asset dollar from Medicaid.', NULL),
('ltc', 'hard', 'Long-Term Care Partnership programs generally require that policies sold to younger purchasers include:', '["A lifetime benefit period","Zero elimination period","A return-of-premium rider","Inflation protection"]'::jsonb, 'Inflation protection', 'To keep benefits meaningful decades later, partnership rules require inflation protection on policies sold to younger buyers.', 'Partnership + young buyer = inflation protection required.', NULL),
('ltc', 'medium', 'When selling long-term care insurance, insurers are generally required to do what regarding inflation protection?', '["Offer the applicant the option to purchase inflation protection","Include it automatically at no charge","Prohibit it on policies sold after age 70","Offer it only with lifetime benefit periods"]'::jsonb, 'Offer the applicant the option to purchase inflation protection', 'LTC regulations require insurers to offer inflation protection; the applicant may reject it, but the offer must be made.', 'Inflation protection must at least be offered.', NULL),
('ltc', 'easy', 'Which of the following is a common exclusion in long-term care policies?', '["Care for Alzheimer''s disease","Care resulting from intentionally self-inflicted injury","Skilled nursing care","Home health care"]'::jsonb, 'Care resulting from intentionally self-inflicted injury', 'Common LTC exclusions include self-inflicted injury, war, and care payable by government programs; Alzheimer''s and other organic cognitive disorders cannot be excluded.', 'LTC excludes self-inflicted and war — never Alzheimer''s.', NULL),
('ltc', 'medium', 'To protect against unintentional lapse, long-term care insurers must generally give applicants the right to:', '["Designate a third party to receive notice before the policy lapses for nonpayment","Skip one premium payment each year","Pay premiums every five years","Assign the policy to the state"]'::jsonb, 'Designate a third party to receive notice before the policy lapses for nonpayment', 'Because LTC buyers may develop cognitive impairment, applicants may name a third party who receives lapse notices so coverage is not lost unintentionally.', 'LTC lapse protection = third-party notice designation.', NULL),
('ltc', 'medium', 'Individual long-term care policies must generally be renewable on at least what basis?', '["Optionally renewable","Nonrenewable term","Guaranteed renewable","Cancelable"]'::jsonb, 'Guaranteed renewable', 'LTC regulations require at least guaranteed renewability: the insurer must renew coverage, though premiums may be raised on a class basis.', 'LTC must be at least guaranteed renewable.', NULL),
('ltc', 'easy', 'When soliciting long-term care insurance, a producer is generally required to deliver which consumer publication?', '["A long-term care insurance shopper''s guide","The insurer''s annual financial statement","A Medicare & You handbook","The state insurance code"]'::jsonb, 'A long-term care insurance shopper''s guide', 'LTC marketing standards require delivery of a shopper''s guide so consumers can compare policies and understand long-term care coverage before buying.', 'An LTC sale puts the shopper''s guide in the buyer''s hands.', NULL),
('ltc', 'medium', 'In determining whether a long-term care policy purchase is appropriate for an applicant, a producer should primarily consider the applicant''s:', '["Ability to pay premiums and existing coverage and resources","Political affiliation","Credit card balances only","Preferred hospital network"]'::jsonb, 'Ability to pay premiums and existing coverage and resources', 'LTC suitability standards focus on whether the applicant can afford the coverage and whether it fits their existing coverage, assets, and needs.', 'LTC suitability: can they afford it, and do they need it.', NULL),
('ltc', 'hard', 'Modern long-term care policies are prohibited from conditioning eligibility for nursing home benefits on:', '["A prior hospital stay","Physician certification","A completed claim form","An elimination period"]'::jsonb, 'A prior hospital stay', 'Regulations prohibit requiring prior hospitalization or a prior level of care as a condition for LTC benefits.', 'No prior-hospitalization requirement is allowed in LTC.', NULL),
('group_health', 'easy', 'In group health insurance, the master contract is issued to the:', '["Employer or other group sponsor","Each individual employee","State insurance department","Third-party administrator"]'::jsonb, 'Employer or other group sponsor', 'The group sponsor holds the master policy; covered members receive certificates of coverage as evidence of their benefits.', 'Group: the employer holds the policy, workers hold certificates.', NULL),
('group_health', 'medium', 'When a group changes insurance carriers, a coinsurance and deductible carryover provision allows:', '["Amounts already credited under the old plan to count toward the new plan''s deductibles","Employees to keep both plans indefinitely","The new insurer to deny all pending claims","Premium refunds from the old carrier"]'::jsonb, 'Amounts already credited under the old plan to count toward the new plan''s deductibles', 'Carryover provisions prevent employees from having to satisfy a full new deductible mid-year when the employer switches carriers.', 'Carrier change: deductible credit carries over.', NULL),
('group_health', 'medium', 'A noncontributory group health plan, in which the employer pays the entire premium, typically requires what level of employee participation?', '["100 percent of eligible employees","75 percent of eligible employees","50 percent of eligible employees","No minimum participation"]'::jsonb, '100 percent of eligible employees', 'When employees pay nothing, all eligible employees must generally be covered; contributory plans typically require around 75 percent participation.', 'Employer pays all = everyone participates (100%).', NULL),
('group_health', 'medium', 'Minimum participation requirements in group insurance exist primarily to:', '["Reduce adverse selection","Increase producer commissions","Satisfy federal tax law","Guarantee dividends to the employer"]'::jsonb, 'Reduce adverse selection', 'Requiring broad participation keeps healthy members in the pool, preventing a group made up mostly of those expecting claims.', 'Participation rules keep the healthy in the pool.', NULL),
('group_health', 'easy', 'To be eligible for group insurance, a group must generally have been formed for a purpose:', '["Other than obtaining insurance","Related to purchasing insurance at a discount","Approved by the NAIC","Involving at least 500 members"]'::jsonb, 'Other than obtaining insurance', 'Eligible groups — employers, associations, unions — must exist for reasons other than buying insurance, which guards against adverse selection.', 'Groups must exist for reasons beyond insurance.', NULL);

-- Batch 5: group_health (6-17 of 17) + medical_plans (1-8 of 17)
INSERT INTO public.questions (domain, difficulty, question, options, correct, explanation, know_this, state_specific) VALUES
('group_health', 'medium', 'A probationary (waiting) period in an employer group health plan is the time:', '["A new employee must wait after hire before becoming eligible for coverage","Between claim submission and payment","During which preexisting conditions are fully covered","The insurer has to contest the master contract"]'::jsonb, 'A new employee must wait after hire before becoming eligible for coverage', 'The probationary period is the waiting time before a newly hired employee becomes eligible to enroll in the group plan.', 'Probationary period: new hires wait before joining the plan.', NULL),
('group_health', 'medium', 'Under the coordination-of-benefits birthday rule, when a dependent child is covered under both parents'' group plans, primary coverage is provided by the plan of the parent:', '["Whose birthday falls earlier in the calendar year","Who is older","Who earns more income","Who enrolled the child first"]'::jsonb, 'Whose birthday falls earlier in the calendar year', 'The birthday rule assigns primary responsibility to the plan of the parent whose birth month and day come first in the calendar year, regardless of age.', 'Birthday rule: earlier birthday in the year = primary plan.', NULL),
('group_health', 'medium', 'Which event would NOT entitle a covered employee to elect COBRA continuation coverage?', '["Termination for gross misconduct","Voluntary resignation","Reduction in work hours below the eligibility threshold","Layoff due to downsizing"]'::jsonb, 'Termination for gross misconduct', 'COBRA rights apply to most terminations and hour reductions, but termination for gross misconduct is the exception that forfeits continuation rights.', 'COBRA covers most exits — but not gross misconduct.', NULL),
('group_health', 'medium', 'Under COBRA, the premium charged to a continuing qualified beneficiary may be up to:', '["100% of the group rate","102% of the group rate","50% of the group rate","125% of the group rate"]'::jsonb, '102% of the group rate', 'COBRA continuants can be charged the full group premium plus a 2 percent administrative fee, for a total of 102 percent.', 'COBRA premium: full cost plus 2% admin fee.', NULL),
('group_health', 'medium', 'Federal COBRA continuation requirements generally apply to employers with at least how many employees?', '["2","20","50","100"]'::jsonb, '20', 'COBRA applies to group health plans of employers with 20 or more employees; smaller groups rely on state continuation laws.', 'COBRA kicks in at 20 employees.', NULL),
('group_health', 'medium', 'State group health continuation laws are especially important for employees of:', '["Small employers not subject to federal COBRA","Federal government agencies","Multinational corporations","Employers with more than 500 workers"]'::jsonb, 'Small employers not subject to federal COBRA', 'Because COBRA generally applies only to employers with 20 or more employees, state continuation laws fill the gap for smaller groups.', 'Too small for COBRA? State continuation steps in.', NULL),
('group_health', 'medium', 'An employer that self-funds its employee health plan:', '["Assumes the financial risk of paying employee health claims itself","Transfers all claim risk to an insurer for a fixed premium","Cannot use a third-party administrator","Is exempt from paying claims over a set amount"]'::jsonb, 'Assumes the financial risk of paying employee health claims itself', 'A self-funded employer pays claims from its own assets rather than buying insurance, though it may hire a third-party administrator and buy stop-loss coverage.', 'Self-funded = the employer is the risk-bearer.', NULL),
('group_health', 'hard', 'Self-funded employer health plans governed by ERISA are significant in state regulation because they are generally:', '["Exempt from state insurance mandates that apply to insured plans","Subject to double state premium taxes","Regulated only by county governments","Prohibited in most states"]'::jsonb, 'Exempt from state insurance mandates that apply to insured plans', 'ERISA preemption means state mandated-benefit laws generally do not reach self-funded plans, unlike fully insured group policies.', 'ERISA self-funded plans sidestep state benefit mandates.', NULL),
('group_health', 'hard', 'A self-funded employer purchases coverage that reimburses the plan when any one participant''s claims exceed a set amount. This is called:', '["Aggregate stop-loss coverage","Specific stop-loss coverage","Reinsurance ceding","Excess interest coverage"]'::jsonb, 'Specific stop-loss coverage', 'Specific (individual) stop-loss caps the plan''s exposure per person; aggregate stop-loss caps total plan claims for the year.', 'Specific = one person''s claims; aggregate = the whole plan''s.', NULL),
('group_health', 'hard', 'Multiple Employer Welfare Arrangements (MEWAs) are notable from a regulatory standpoint because they:', '["Remain subject to state insurance regulation despite ERISA","Are regulated exclusively by the federal government","Are exempt from all solvency requirements","May only cover government employees"]'::jsonb, 'Remain subject to state insurance regulation despite ERISA', 'Unlike single-employer ERISA plans, MEWAs are subject to state insurance oversight, largely because of historical solvency failures.', 'MEWAs answer to the states, ERISA or not.', NULL),
('group_health', 'hard', 'When an actively working employee of a small employer (fewer than 20 employees) is also enrolled in Medicare, which coverage generally pays first?', '["Medicare","The employer group plan","Medicaid","The employee chooses each year"]'::jsonb, 'Medicare', 'Medicare secondary payer rules make the group plan primary only for employers with 20 or more employees; below that, Medicare pays primary.', 'Under-20 employer group: Medicare pays primary.', NULL),
('group_health', 'medium', 'Under the Age Discrimination in Employment Act (ADEA), employers must generally:', '["Offer older active employees the same group health benefits offered to younger employees","Retire employees at age 65","Reduce benefits for anyone over age 60","Exclude workers over 70 from group plans"]'::jsonb, 'Offer older active employees the same group health benefits offered to younger employees', 'ADEA requires that actively working older employees receive group health benefits on the same terms as younger workers.', 'ADEA: active older workers keep equal group benefits.', NULL),
('medical_plans', 'easy', 'A traditional indemnity (fee-for-service) medical plan differs from an HMO in that the indemnity plan:', '["Reimburses covered expenses after care is received from a provider of the insured''s choice","Prepays a fixed fee covering all future care","Requires primary care physician referrals","Provides services rather than dollar benefits"]'::jsonb, 'Reimburses covered expenses after care is received from a provider of the insured''s choice', 'Indemnity plans reimburse expenses on a fee-for-service basis with free provider choice, while HMOs provide prepaid services through a network.', 'Indemnity = any doctor, reimbursed after the fact.', NULL),
('medical_plans', 'easy', 'A comprehensive major medical policy typically combines:', '["A deductible, coinsurance, and broad coverage of hospital and medical expenses","First-dollar coverage with no cost sharing","Accident-only benefits with a life insurance rider","Dental and vision benefits only"]'::jsonb, 'A deductible, coinsurance, and broad coverage of hospital and medical expenses', 'Comprehensive major medical provides broad hospital, surgical, and medical coverage subject to a deductible and coinsurance, usually with high maximums.', 'Comprehensive major med = deductible + coinsurance + broad coverage.', NULL),
('medical_plans', 'easy', 'The amount an insured must pay out of pocket each year before the medical plan begins paying benefits is the:', '["Copayment","Deductible","Stop-loss limit","Premium"]'::jsonb, 'Deductible', 'The deductible is the initial amount of covered expenses the insured pays before the insurer begins sharing costs.', 'Deductible first, then the plan pays.', NULL),
('medical_plans', 'hard', 'A carryover provision in a major medical policy allows expenses incurred:', '["In the last three months of the year to apply toward the next year''s deductible","At any time to be reimbursed at 100 percent","By one family member to be disregarded","After the deductible to be counted twice"]'::jsonb, 'In the last three months of the year to apply toward the next year''s deductible', 'Under a carryover provision, expenses from the final months of the year that were applied to that year''s deductible also count toward the next year''s deductible.', 'Late-year expenses can carry into next year''s deductible.', NULL),
('medical_plans', 'easy', 'Under an 80/20 coinsurance provision, after the deductible the insurer pays 80 percent of covered expenses and the insured pays:', '["20 percent","80 percent","50 percent","Nothing"]'::jsonb, '20 percent', 'Coinsurance splits covered expenses after the deductible; in an 80/20 plan the insured''s share is 20 percent, usually until an out-of-pocket maximum is reached.', '80/20: the plan pays 80, you pay 20.', NULL),
('medical_plans', 'medium', 'Which individual is eligible to contribute to a Health Savings Account (HSA)?', '["Someone covered by a qualified high-deductible health plan and not enrolled in Medicare","Anyone with any form of health insurance","Only self-employed individuals","Anyone claimed as a dependent on another person''s tax return"]'::jsonb, 'Someone covered by a qualified high-deductible health plan and not enrolled in Medicare', 'HSA eligibility requires HDHP coverage, no other disqualifying coverage, no Medicare enrollment, and not being claimed as a dependent.', 'HSA: HDHP required, no Medicare, not a dependent.', NULL),
('medical_plans', 'medium', 'HSA distributions used for qualified medical expenses are:', '["Received income tax free","Taxed as ordinary income","Subject to capital gains tax","Taxable only after age 65"]'::jsonb, 'Received income tax free', 'HSAs offer triple tax advantages: deductible contributions, tax-deferred growth, and tax-free withdrawals for qualified medical expenses.', 'Qualified HSA withdrawals = tax-free.', NULL),
('medical_plans', 'hard', 'An HSA owner under age 65 who withdraws funds for nonqualified purposes generally owes income tax plus a penalty of:', '["10 percent","20 percent","6 percent","50 percent"]'::jsonb, '20 percent', 'Nonqualified HSA distributions before age 65 are included in income and subject to an additional 20 percent penalty tax.', 'Nonqualified HSA withdrawal: taxes plus a 20% penalty.', NULL);

-- Batch 6: medical_plans (9-17 of 17) + disability_income (1-11 of 15)
INSERT INTO public.questions (domain, difficulty, question, options, correct, explanation, know_this, state_specific) VALUES
('medical_plans', 'easy', 'Which statement about HSA portability is TRUE?', '["The account belongs to the individual and moves with them when they change employers","The account is forfeited upon any job change","Unused balances expire at year-end","The employer owns all contributions"]'::jsonb, 'The account belongs to the individual and moves with them when they change employers', 'An HSA is individually owned; balances roll over year to year and stay with the account holder through job changes.', 'HSAs follow the worker, not the job.', NULL),
('medical_plans', 'medium', 'Preauthorization (prospective review) in managed care requires:', '["Approval of a proposed service before it is performed","Review of care while the patient is hospitalized","An audit of claims after payment","Second opinions for all prescriptions"]'::jsonb, 'Approval of a proposed service before it is performed', 'Prospective review evaluates the necessity of nonemergency services before they are delivered, controlling costs up front.', 'Prospective review happens before treatment.', NULL),
('medical_plans', 'medium', 'Concurrent review, as a utilization management tool, takes place:', '["While the insured is receiving care, such as during a hospital stay","Before treatment is scheduled","After the claim has been paid","Only when the insured files an appeal"]'::jsonb, 'While the insured is receiving care, such as during a hospital stay', 'Concurrent review monitors ongoing care — commonly the length of a hospital stay — while it is happening.', 'Concurrent review = monitoring care as it happens.', NULL),
('medical_plans', 'medium', 'Under federal law, group health plans covering childbirth generally may not restrict hospital stays for a normal vaginal delivery to less than:', '["24 hours","48 hours","12 hours","96 hours"]'::jsonb, '48 hours', 'Federal maternity-stay rules set minimums of 48 hours for a normal delivery and 96 hours for a cesarean delivery.', 'Maternity minimums: 48 hours normal, 96 hours cesarean.', NULL),
('medical_plans', 'medium', 'Which of the following is among the ACA''s essential health benefits that individual and small-group plans must cover?', '["Maternity and newborn care","Cosmetic surgery","Adult long-term custodial care","Concierge medicine membership fees"]'::jsonb, 'Maternity and newborn care', 'The ACA''s essential health benefits include categories such as maternity and newborn care, prescription drugs, and mental health services.', 'Maternity care is an ACA essential health benefit.', NULL),
('medical_plans', 'hard', 'The ACA''s metal tiers (bronze, silver, gold, platinum) classify plans based on:', '["Actuarial value — the average share of costs the plan pays","Provider network size","Insurer financial strength ratings","Monthly premium amount alone"]'::jsonb, 'Actuarial value — the average share of costs the plan pays', 'Metal tiers reflect actuarial value: the average percentage of covered costs the plan pays, from about 60 percent for bronze to 90 percent for platinum.', 'Metal tiers measure the plan''s share of costs, not its quality.', NULL),
('medical_plans', 'hard', 'ACA catastrophic plans are generally available only to:', '["Individuals under age 30 or those with a hardship exemption","Anyone over age 55","Small business owners","Medicare beneficiaries"]'::jsonb, 'Individuals under age 30 or those with a hardship exemption', 'Catastrophic plans carry very high deductibles and are limited to people under 30 or those qualifying for a hardship or affordability exemption.', 'Catastrophic plans: under-30s and hardship cases only.', NULL),
('medical_plans', 'medium', 'Cost-sharing reductions for eligible marketplace enrollees are available only if the enrollee purchases which metal tier?', '["Bronze","Gold","Silver","Platinum"]'::jsonb, 'Silver', 'Cost-sharing reductions lower deductibles and copays for eligible enrollees, but only when they select a silver marketplace plan.', 'Cost-sharing reductions ride only on silver plans.', NULL),
('medical_plans', 'easy', 'Under the ACA, group and individual health plans providing dependent coverage must make it available to adult children up to age:', '["21","26","18","30"]'::jsonb, '26', 'The ACA requires plans offering dependent coverage to cover adult children until they turn 26, regardless of student or marital status.', 'Kids can stay on the plan until 26.', NULL),
('disability_income', 'medium', 'Under an any-occupation definition of total disability, benefits are payable only if the insured cannot perform:', '["The duties of any occupation for which they are reasonably suited by education, training, or experience","The primary duties of their own occupation","Any job that exists anywhere in the economy, including minimum-wage work","Normal household activities"]'::jsonb, 'The duties of any occupation for which they are reasonably suited by education, training, or experience', 'The any-occupation standard in commercial policies is tied to work the insured is reasonably suited for — stricter than own-occupation but not literally any job.', 'Any-occ = cannot do work you are reasonably suited for.', NULL),
('disability_income', 'hard', 'A recurrent disability provision provides that if an insured returns to work but becomes disabled again from the same cause within a specified period, the second disability:', '["Is treated as a continuation of the first, with no new elimination period","Is automatically denied","Requires a doubled elimination period","Must be underwritten as a new policy"]'::jsonb, 'Is treated as a continuation of the first, with no new elimination period', 'A relapse within the stated timeframe counts as the same claim, so the insured does not have to satisfy a fresh elimination period.', 'Quick relapse = same claim, no new waiting period.', NULL),
('disability_income', 'easy', 'In disability income insurance, the benefit period is:', '["The maximum length of time benefits will be paid during a disability","The time before benefits begin","The interval between premium payments","The period during which the policy can be contested"]'::jsonb, 'The maximum length of time benefits will be paid during a disability', 'The benefit period defines how long monthly benefits continue — for example two years, five years, or to age 65.', 'Benefit period = how long the checks keep coming.', NULL),
('disability_income', 'easy', 'Choosing a longer elimination period on a disability income policy will generally result in:', '["A lower premium","A higher premium","A longer benefit period","Higher monthly benefits"]'::jsonb, 'A lower premium', 'The elimination period is the time the insured self-insures before benefits start; accepting a longer wait reduces the premium.', 'Longer wait = cheaper premium.', NULL),
('disability_income', 'medium', 'The waiver of premium feature in a disability income policy provides that:', '["Premiums are waived after the insured has been totally disabled for a specified time","The first year''s premium is free","Premiums are refunded at age 65","The insurer waives all underwriting requirements"]'::jsonb, 'Premiums are waived after the insured has been totally disabled for a specified time', 'Once the insured has been disabled for the stated period, future premiums are waived while the disability continues, and premiums paid during that period are often refunded.', 'Disabled long enough? Premiums get waived.', NULL),
('disability_income', 'medium', 'The probationary period in a disability income policy is best described as:', '["A period after policy issue during which sickness-related disabilities are not covered","The time between disability onset and the first benefit payment","A trial period for returning the policy","The window for claim investigation"]'::jsonb, 'A period after policy issue during which sickness-related disabilities are not covered', 'The probationary period applies once, at issue, and typically applies to sickness (not accidents) to prevent adverse selection; the elimination period applies to each claim.', 'Probationary = new-policy waiting; elimination = new-claim waiting.', NULL),
('disability_income', 'medium', 'A partial disability benefit typically pays:', '["A reduced benefit when the insured can perform some but not all job duties or works part-time","Double the total disability benefit","Benefits only after age 65","The full benefit for life"]'::jsonb, 'A reduced benefit when the insured can perform some but not all job duties or works part-time', 'Partial disability benefits pay a reduced amount — often a percentage of the total benefit — when the insured can work in a limited capacity.', 'Partial disability = a partial check.', NULL),
('disability_income', 'hard', 'A Social Insurance Supplement (SIS) rider in a disability income policy is designed to:', '["Pay benefits when Social Security disability benefits are denied, delayed, or reduced","Replace Medicare coverage","Increase the insured''s Social Security credits","Pay the insured''s payroll taxes during disability"]'::jsonb, 'Pay benefits when Social Security disability benefits are denied, delayed, or reduced', 'The SIS rider fills the gap when strict Social Security disability standards result in denied or delayed benefits, and offsets when those benefits are paid.', 'SIS fills the gap while Social Security says no.', NULL),
('disability_income', 'medium', 'Nonoccupational disability coverage is commonly used in group plans because:', '["Work-related disabilities are already covered by workers compensation","Employees rarely become ill","It is required by ERISA","It provides 24-hour coverage"]'::jsonb, 'Work-related disabilities are already covered by workers compensation', 'Group disability plans often exclude on-the-job disabilities since workers compensation covers them, avoiding duplicate benefits.', 'Group DI skips work injuries — workers comp has those.', NULL),
('disability_income', 'medium', 'Group long-term disability (LTD) benefits are typically limited to about what portion of the employee''s earnings?', '["60 percent","100 percent","25 percent","90 percent"]'::jsonb, '60 percent', 'Group LTD plans commonly replace about 60 percent of earnings, keeping benefits below full pay to preserve the incentive to return to work.', 'Group LTD targets roughly 60% of pay.', NULL),
('disability_income', 'easy', 'Compared with long-term disability coverage, group short-term disability (STD) is characterized by:', '["Shorter benefit periods and shorter elimination periods","Longer benefit periods","Coverage only for work-related injuries","Benefits payable for life"]'::jsonb, 'Shorter benefit periods and shorter elimination periods', 'STD begins quickly and pays for a limited time (often weeks to months); LTD begins after a longer wait and pays for years.', 'STD: quick to start, quick to end.', NULL);

-- Batch 7: disability_income (12-15 of 15) + health_basics (1-14 of 14) + health_plan_types (1-2 of 13)
INSERT INTO public.questions (domain, difficulty, question, options, correct, explanation, know_this, state_specific) VALUES
('disability_income', 'medium', 'A disability buy-sell policy is designed to provide funds so that:', '["The remaining business owners can purchase a totally disabled owner''s interest in the business","The disabled owner can pay personal medical bills","Employees receive severance pay","The business can pay its federal taxes"]'::jsonb, 'The remaining business owners can purchase a totally disabled owner''s interest in the business', 'A disability buy-sell agreement, funded by insurance, provides the cash for co-owners to buy out an owner who becomes totally and permanently disabled.', 'DI buy-sell funds the buyout of a disabled owner.', NULL),
('disability_income', 'hard', 'Social Security disability income benefits begin after a waiting period of:', '["Thirty days","Five months","Twelve months","Two years"]'::jsonb, 'Five months', 'Social Security disability benefits are subject to a five-month waiting period, with benefits beginning in the sixth full month of disability.', 'SSDI waits five full months.', NULL),
('disability_income', 'hard', 'To qualify as disabled for Social Security disability benefits, an individual''s impairment must be expected to:', '["Last at least 12 months or result in death","Last at least 90 days","Prevent part-time work for 6 months","Reduce earnings by 20 percent"]'::jsonb, 'Last at least 12 months or result in death', 'Social Security uses a strict standard: inability to engage in substantial gainful activity due to an impairment expected to last at least 12 months or result in death.', 'The SSDI standard: 12 months or fatal.', NULL),
('disability_income', 'medium', 'In a key person disability income policy, the premiums are paid by, and benefits are payable to:', '["The business","The key employee","The employee''s family","The state"]'::jsonb, 'The business', 'The business owns the policy, pays the premiums, and receives the benefits to offset losses while a key employee is disabled.', 'Key person DI: the business pays, the business collects.', NULL),
('health_basics', 'medium', 'For purposes of accident and health insurance, an accidental injury is generally one that is:', '["Unforeseen and unintended by the insured","Expected as a result of the insured''s occupation","Intentionally self-inflicted","Caused by sickness"]'::jsonb, 'Unforeseen and unintended by the insured', 'Accidental injury means unforeseen, unintended bodily injury — distinguishing it from sickness and from intentional or expected harm.', 'Accidental = unexpected and unintended.', NULL),
('health_basics', 'medium', 'In health insurance, a service is considered medically necessary when it is:', '["Appropriate and consistent with accepted standards of practice for diagnosing or treating the condition","Requested by the insured","The most expensive available option","Provided in a hospital setting"]'::jsonb, 'Appropriate and consistent with accepted standards of practice for diagnosing or treating the condition', 'Medical necessity ties coverage to care that is appropriate under generally accepted standards of medical practice, not to patient preference or setting.', 'Medically necessary = appropriate care by accepted standards.', NULL),
('health_basics', 'easy', 'Disability income insurance is designed primarily to protect against which type of loss?', '["Loss of income due to the insured''s inability to work","Hospital room and board expenses","Long-term custodial care costs","Dental expenses"]'::jsonb, 'Loss of income due to the insured''s inability to work', 'The principal types of health-related losses are income loss, medical expense, dental expense, and long-term care expense; disability income covers the first.', 'DI replaces paychecks, not medical bills.', NULL),
('health_basics', 'easy', 'A hospital indemnity policy pays:', '["A fixed daily amount during hospitalization, regardless of actual expenses incurred","All hospital charges in full","Only the surgeon''s fees","Benefits directly to the hospital based on billed charges"]'::jsonb, 'A fixed daily amount during hospitalization, regardless of actual expenses incurred', 'Hospital indemnity is a limited policy paying a stated daily cash benefit to the insured while hospitalized, independent of the actual bill.', 'Hospital indemnity: flat daily cash, not expense reimbursement.', NULL),
('health_basics', 'medium', 'Under a credit disability policy, if the insured debtor becomes disabled, benefits are paid to:', '["The creditor, to cover the loan payments","The insured, in a lump sum","The insured''s beneficiary","The state insurance fund"]'::jsonb, 'The creditor, to cover the loan payments', 'Credit disability insurance makes the debtor''s loan payments during disability, with the creditor as beneficiary and coverage limited to the debt.', 'Credit disability pays the lender, not you.', NULL),
('health_basics', 'medium', 'When selling a limited health policy such as accident-only coverage, the producer must ensure the applicant understands that:', '["The policy covers only the specific perils named and is not comprehensive coverage","The policy covers all sicknesses","Benefits are unlimited","The coverage duplicates major medical insurance"]'::jsonb, 'The policy covers only the specific perils named and is not comprehensive coverage', 'Limited policies must be clearly identified as limited; the insured must be notified of the restricted coverage and amounts.', 'Limited policies must be sold as limited.', NULL),
('health_basics', 'medium', 'Under the uniform notice of claim provision, an insured should give the insurer notice of a claim within how many days after a covered loss?', '["20 days","5 days","90 days","180 days"]'::jsonb, '20 days', 'The standard notice of claim provision calls for written notice within 20 days of the loss, or as soon as reasonably possible.', 'Notice of claim: 20 days.', NULL),
('health_basics', 'hard', 'Under the uniform proof of loss provision, the insured must generally furnish written proof of loss within:', '["20 days after the loss","90 days after the loss","30 days after the loss","One year after the loss"]'::jsonb, '90 days after the loss', 'Proof of loss is due within 90 days, though a claim cannot be denied for late proof if it was not reasonably possible to comply in time.', 'Proof of loss: 90 days.', NULL),
('health_basics', 'medium', 'Under the change of occupation provision, if an insured changes to a more hazardous occupation, the insurer may:', '["Reduce benefits to what the premium would have purchased at the more hazardous occupation''s rates","Cancel the policy immediately","Double the premium retroactively","Deny all future claims"]'::jsonb, 'Reduce benefits to what the premium would have purchased at the more hazardous occupation''s rates', 'The provision adjusts benefits — not coverage — so the premium paid buys the benefit level appropriate to the riskier occupation.', 'Riskier job = benefits scale down, the policy stays.', NULL),
('health_basics', 'medium', 'If a health insured''s age was misstated on the application, the misstatement of age provision allows the insurer to:', '["Adjust benefits to what the premiums paid would have purchased at the correct age","Void the policy at any time","Keep all premiums and deny the claim","Charge triple premiums going forward"]'::jsonb, 'Adjust benefits to what the premiums paid would have purchased at the correct age', 'Misstated age does not void coverage; benefits are simply recalculated to the amount the premium would have bought at the true age.', 'Wrong age = benefits adjusted, not denied.', NULL),
('health_basics', 'hard', 'After a lapsed health policy is reinstated, coverage for sickness typically begins:', '["After a short waiting period (commonly 10 days), while accidents are covered immediately","Immediately for both sickness and accidents","After 90 days for both sickness and accidents","Only at the next policy anniversary"]'::jsonb, 'After a short waiting period (commonly 10 days), while accidents are covered immediately', 'Reinstatement restores accident coverage at once but imposes a brief sickness waiting period to prevent people from reinstating only after becoming ill.', 'Reinstatement: accidents now, sickness after 10 days.', NULL),
('health_basics', 'medium', 'A noncancelable disability policy guarantees that the insurer:', '["Cannot cancel the policy or increase the premium as long as premiums are paid","May increase premiums on a class basis","May cancel with 30 days notice","Must add riders upon request"]'::jsonb, 'Cannot cancel the policy or increase the premium as long as premiums are paid', 'Noncancelable is the strongest renewability guarantee: both continued coverage and the premium schedule are locked in.', 'Noncan = premiums locked, policy locked.', NULL),
('health_basics', 'medium', 'Under a guaranteed renewable health policy, the insurer may:', '["Increase premiums on a class basis but must renew the coverage","Cancel individual policies for excessive claims","Refuse renewal for health reasons","Never change premiums"]'::jsonb, 'Increase premiums on a class basis but must renew the coverage', 'Guaranteed renewable policies must be renewed, but premiums can rise for entire classes of insureds — unlike noncancelable policies with fixed premiums.', 'Guaranteed renewable: must renew, but class-wide rate hikes allowed.', NULL),
('health_basics', 'medium', 'When replacing an existing accident and health policy, an important consideration for the client is that the new policy may:', '["Impose new preexisting condition limitations or waiting periods","Automatically carry over all prior policy benefits","Be issued without any underwriting","Guarantee lower premiums"]'::jsonb, 'Impose new preexisting condition limitations or waiting periods', 'Replacement can restart preexisting condition limitations, probationary periods, and underwriting — key reasons replacement requires careful comparison.', 'Replacement restarts the clocks — preexisting and waiting periods.', NULL),
('health_plan_types', 'easy', 'A key characteristic of a health maintenance organization (HMO) is that it:', '["Provides health care services to members in exchange for prepaid periodic fees","Reimburses members for expenses after care from any provider","Sells only accident coverage","Operates without any provider network"]'::jsonb, 'Provides health care services to members in exchange for prepaid periodic fees', 'HMOs deliver care on a prepaid, service basis through their own network, rather than reimbursing expenses like an indemnity insurer.', 'HMOs deliver care, not reimbursement checks.', NULL),
('health_plan_types', 'medium', 'HMO members are generally required to receive nonemergency care:', '["Within the HMO''s defined service area and provider network","Anywhere in the country","Only at university hospitals","From federal facilities"]'::jsonb, 'Within the HMO''s defined service area and provider network', 'HMOs operate within a defined geographic service area; nonemergency care must come from network providers inside that area.', 'HMO care stays inside the service area.', NULL);

-- Batch 8: health_plan_types (3-13 of 13) + dental (1-7 of 7) + aca_hipaa (1-2 of 7)
INSERT INTO public.questions (domain, difficulty, question, options, correct, explanation, know_this, state_specific) VALUES
('health_plan_types', 'easy', 'HMOs emphasize preventive care primarily because:', '["Detecting and treating problems early lowers overall health care costs","State law prohibits treating chronic illness","It increases hospital admissions","Members demand fewer services"]'::jsonb, 'Detecting and treating problems early lowers overall health care costs', 'Since HMOs bear the cost of care on a prepaid basis, preventing illness and catching problems early directly reduces their claim costs.', 'HMOs prevent now to save later.', NULL),
('health_plan_types', 'medium', 'In managed care, the gatekeeper concept is designed to:', '["Control costs by having a primary care physician coordinate and approve access to specialists","Restrict enrollment to healthy applicants","Limit coverage to emergency care","Require hospital-only treatment"]'::jsonb, 'Control costs by having a primary care physician coordinate and approve access to specialists', 'The gatekeeper (primary care physician) coordinates all care and must generally authorize specialist referrals, controlling utilization and cost.', 'The gatekeeper PCP controls the road to specialists.', NULL),
('health_plan_types', 'medium', 'Cost sharing in an HMO typically takes the form of:', '["Small fixed copayments for services","Large annual deductibles with 50 percent coinsurance","Full billed charges up to a threshold","Premium refunds for low utilization"]'::jsonb, 'Small fixed copayments for services', 'HMO members typically pay modest copayments per visit or service rather than the large deductibles and coinsurance of indemnity plans.', 'HMOs use copays, not big deductibles.', NULL),
('health_plan_types', 'medium', 'Physicians participating in a preferred provider organization (PPO) are generally:', '["Independent providers who contract to serve plan members at negotiated, discounted fees","Salaried employees of the insurer","Prohibited from treating non-PPO patients","Paid a fixed amount per enrollee regardless of services rendered"]'::jsonb, 'Independent providers who contract to serve plan members at negotiated, discounted fees', 'PPO providers remain independent and are paid discounted fee-for-service rates under contract; they may also treat patients outside the PPO.', 'PPO doctors are contractors at discounted fee-for-service rates.', NULL),
('health_plan_types', 'hard', 'A closed panel arrangement exists when:', '["Members must use the plan''s designated physicians, who typically serve only plan members","Any licensed physician may treat plan members","The plan has no physician network","Members may see any specialist without a referral"]'::jsonb, 'Members must use the plan''s designated physicians, who typically serve only plan members', 'In a closed panel, care comes only from the plan''s own physicians; an open panel lets outside physicians participate and treat their own patients as well.', 'Closed panel = plan doctors only.', NULL),
('health_plan_types', 'medium', 'Under a point-of-service (POS) plan, the member decides whether to use network or out-of-network providers:', '["Each time care is needed","Once, at annual enrollment only","Never — the plan decides","Only with employer approval"]'::jsonb, 'Each time care is needed', 'POS plans let the member choose HMO-style network care or PPO-style out-of-network care at the point of each service, with different cost sharing.', 'POS: choose your path at the point of service.', NULL),
('health_plan_types', 'medium', 'Service plans such as traditional Blue Cross/Blue Shield organizations are distinctive because they:', '["Pay contracted providers directly for services rather than reimbursing the subscriber","Provide cash benefits directly to insureds","Never contract with hospitals","Offer only dental benefits"]'::jsonb, 'Pay contracted providers directly for services rather than reimbursing the subscriber', 'Service plans contract with providers and pay them directly for subscriber care, in contrast to indemnity insurers that reimburse the insured.', 'Service plans pay the provider, not the patient.', NULL),
('health_plan_types', 'easy', 'Participants in HMOs and service plans are typically referred to as:', '["Subscribers or members","Policyowners","Certificate creditors","Annuitants"]'::jsonb, 'Subscribers or members', 'Because these plans provide services rather than indemnity payments, their participants are called subscribers or members rather than insureds or policyowners.', 'HMO people are subscribers, not policyholders.', NULL),
('health_plan_types', 'medium', 'An HMO member who experiences a medical emergency while traveling outside the service area:', '["Is covered for the emergency care received out of area","Has no coverage of any kind","Must return to the service area before receiving treatment","Pays all costs with no reimbursement"]'::jsonb, 'Is covered for the emergency care received out of area', 'Emergency care is the exception to HMO service-area rules; true emergencies are covered wherever they occur.', 'Emergencies are covered even outside HMO territory.', NULL),
('health_plan_types', 'hard', 'In a staff model HMO, physicians are:', '["Employees of the HMO who typically treat only HMO members","Independent contractors in private practice","Hospital shareholders","Unpaid volunteers"]'::jsonb, 'Employees of the HMO who typically treat only HMO members', 'Staff model HMOs employ their physicians directly, usually in HMO-owned facilities serving only plan members.', 'Staff model: doctors on the HMO payroll.', NULL),
('health_plan_types', 'hard', 'Under an individual practice association (IPA) model HMO, participating physicians:', '["Practice independently in their own offices and contract to treat HMO members alongside other patients","Work exclusively in HMO-owned clinics","Are salaried by the HMO","May not treat any non-HMO patients"]'::jsonb, 'Practice independently in their own offices and contract to treat HMO members alongside other patients', 'The IPA model is an open-panel arrangement: independent physicians contract with the HMO while continuing to see their own non-HMO patients.', 'IPA: private-practice doctors under HMO contract.', NULL),
('dental', 'easy', 'Dentures and fixed bridgework fall under which category of dental treatment?', '["Prosthodontics","Endodontics","Periodontics","Orthodontics"]'::jsonb, 'Prosthodontics', 'Prosthodontics covers artificial replacements for missing teeth, such as dentures and bridgework.', 'Prosthodontics = replacements (dentures, bridges).', NULL),
('dental', 'medium', 'Extraction of an impacted wisdom tooth is classified under which category of dental treatment?', '["Oral surgery","Preventive care","Prosthodontics","Restorative care"]'::jsonb, 'Oral surgery', 'Surgical procedures of the mouth, including extraction of impacted teeth, fall under the oral surgery category.', 'Cutting teeth out = oral surgery.', NULL),
('dental', 'medium', 'A nonscheduled dental plan differs from a scheduled plan in that a nonscheduled plan:', '["Pays benefits based on usual, customary, and reasonable charges rather than a fixed fee list","Pays a flat dollar amount per procedure","Never applies coinsurance","Covers only preventive care"]'::jsonb, 'Pays benefits based on usual, customary, and reasonable charges rather than a fixed fee list', 'Scheduled plans pay from a fixed fee schedule; nonscheduled (comprehensive) plans pay a percentage of UCR charges.', 'Nonscheduled = UCR-based; scheduled = fee list.', NULL),
('dental', 'medium', 'In a typical comprehensive dental plan, which category of services is reimbursed at the highest percentage, often without a deductible?', '["Diagnostic and preventive services","Major restorative services","Orthodontics","Prosthodontics"]'::jsonb, 'Diagnostic and preventive services', 'Plans encourage preventive care by covering exams and cleanings at the richest level — often 100 percent with no deductible — while major services carry more cost sharing.', 'Cleanings and exams get the richest dental coverage.', NULL),
('dental', 'hard', 'A dental plan with an integrated deductible is one in which:', '["Dental expenses may be applied toward the deductible of the insured''s medical plan","Each family member has a separate lifetime deductible","The deductible applies only to orthodontics","No deductible applies to any dental service"]'::jsonb, 'Dental expenses may be applied toward the deductible of the insured''s medical plan', 'An integrated plan combines dental with the medical plan''s deductible, unlike a stand-alone dental plan with its own separate deductible.', 'Integrated deductible: dental and medical share one deductible.', NULL),
('dental', 'hard', 'To minimize adverse selection, group dental plans that allow late enrollment often:', '["Reduce benefits or impose longer waiting periods for late enrollees","Pay double benefits to late enrollees","Waive all waiting periods","Refund premiums to timely enrollees"]'::jsonb, 'Reduce benefits or impose longer waiting periods for late enrollees', 'Because people tend to enroll in dental coverage when they anticipate needing work done, late enrollees often face benefit limits or extended waiting periods.', 'Enroll late in dental, wait longer for benefits.', NULL),
('dental', 'easy', 'Which service is most likely to be excluded from a dental expense plan?', '["Teeth whitening and other cosmetic procedures","Routine cleanings","Fillings","Medically necessary extractions"]'::jsonb, 'Teeth whitening and other cosmetic procedures', 'Cosmetic dentistry is a standard dental plan exclusion, along with duplicate appliances and services covered under workers compensation.', 'Cosmetic dentistry is not covered dentistry.', NULL),
('aca_hipaa', 'medium', 'A self-employed sole proprietor may generally deduct health insurance premiums paid for herself and her family:', '["As an above-the-line deduction against income, without itemizing","Only as an itemized medical expense deduction","Only if she has at least one employee","Not at all"]'::jsonb, 'As an above-the-line deduction against income, without itemizing', 'Self-employed individuals may deduct health insurance premiums for themselves, a spouse, and dependents directly from income without itemizing.', 'Self-employed health premiums: deductible without itemizing.', NULL),
('aca_hipaa', 'hard', 'An individual taxpayer may deduct unreimbursed medical expenses, including medical insurance premiums, only to the extent they exceed:', '["7.5 percent of adjusted gross income","2 percent of adjusted gross income","10 percent of taxable income","50 percent of itemized deductions"]'::jsonb, '7.5 percent of adjusted gross income', 'Unreimbursed medical expenses are deductible only as itemized deductions and only to the extent they exceed 7.5 percent of adjusted gross income.', 'Medical expense deductions start above 7.5% of AGI.', NULL);

-- Batch 9: aca_hipaa (3-7 of 7)
INSERT INTO public.questions (domain, difficulty, question, options, correct, explanation, know_this, state_specific) VALUES
('aca_hipaa', 'easy', 'Premiums an employer pays for employees'' group medical expense coverage are generally:', '["Tax deductible to the employer and not taxable income to the employees","Taxable income to the employees","Nondeductible for the employer","Deductible only for business owners"]'::jsonb, 'Tax deductible to the employer and not taxable income to the employees', 'Employer-paid medical expense premiums are a deductible business expense and are excluded from employees'' taxable income.', 'Employer-paid medical premiums: deductible to them, tax-free to you.', NULL),
('aca_hipaa', 'medium', 'Benefits received by an insured under a personally owned medical expense policy are generally:', '["Not taxable as income","Fully taxable as ordinary income","Taxable above a set dollar amount","Taxed as capital gains"]'::jsonb, 'Not taxable as income', 'Medical expense benefits reimburse actual losses, so they are received income tax free; deducting the same expenses on top of tax-free benefits is not allowed.', 'Medical expense benefits arrive tax-free.', NULL),
('aca_hipaa', 'medium', 'The HIPAA privacy rule primarily restricts:', '["How covered entities use and disclose individually identifiable health information","How much insurers may charge for coverage","Which providers may join plan networks","How claims are coded for billing"]'::jsonb, 'How covered entities use and disclose individually identifiable health information', 'HIPAA''s privacy rule governs the use and disclosure of protected health information by insurers, providers, and clearinghouses, and gives patients access rights.', 'HIPAA privacy = who may see and share your health information.', NULL),
('aca_hipaa', 'hard', 'Under HIPAA nondiscrimination rules, a group health plan may not:', '["Charge a similarly situated individual a higher premium based on health status","Impose an annual open enrollment period","Use a probationary period for new hires","Apply minimum participation requirements"]'::jsonb, 'Charge a similarly situated individual a higher premium based on health status', 'HIPAA prohibits group plans from varying eligibility or premiums among similarly situated individuals based on health status factors.', 'Group plans cannot rate individuals on their health status.', NULL),
('aca_hipaa', 'medium', 'Under the ACA, non-grandfathered health plans must cover certain preventive services:', '["Without imposing deductibles, copayments, or coinsurance","Only after the annual deductible is met","Subject to 50 percent coinsurance","Only under HMO plans"]'::jsonb, 'Without imposing deductibles, copayments, or coinsurance', 'The ACA requires specified preventive services — such as immunizations and recommended screenings — to be covered with no cost sharing when delivered in network.', 'ACA preventive care = no cost sharing.', NULL),
('medicare', 'medium', 'An individual under age 65 may qualify for Medicare based on:', '["End-stage renal disease (permanent kidney failure)","Unemployment","Low income alone","Enrollment in an ACA marketplace plan"]'::jsonb, 'End-stage renal disease (permanent kidney failure)', 'Medicare covers people under 65 with end-stage renal disease, as well as those who have received Social Security disability benefits for the required period; low income alone points to Medicaid, not Medicare.', 'Medicare under 65: disability or kidney failure.', NULL);
