-- Study modules for the Wisconsin Property (22-05), Casualty (22-07), and
-- Personal Lines (22-09) licenses. Lesson bodies live in
-- src/content/study/<id>.jsx (registered in src/lib/studyLessons.js); the
-- license -> module mapping lives in src/lib/licenses.js.
-- Idempotent: existing ids are left untouched.

insert into public.study_modules (id, category, title, summary, estimated_minutes, objectives, sort_order)
values
  ('pc-regulation-wisconsin', 'Property & Casualty',
   'Wisconsin P&C regulation and licensing',
   'Licensing, marketing practices, cancellation and nonrenewal, and the Wisconsin statutes named in the P&C outlines. This is 35% of every P&C exam.',
   40,
   array['Apply ch. 628 licensing and producer-conduct rules',
         'Identify unfair marketing and claim practices',
         'Use s. 631.36 cancellation, nonrenewal, and renewal notice periods',
         'Explain surplus lines, binders, rate standards, and the WIP'],
   16),
  ('property-insurance-basics', 'Property & Casualty',
   'Property insurance principles, valuation, and coinsurance',
   'Insurable interest, hazards, valuation methods, coinsurance math, other-insurance splits, and common property provisions.',
   35,
   array['Calculate ACV and coinsurance recoveries',
         'Distinguish agreed value, stated amount, and functional replacement cost',
         'Apply pro rata and equal-shares other-insurance clauses',
         'Explain subrogation, salvage, liberalization, and mortgage clauses'],
   17),
  ('dwelling-homeowners', 'Property & Casualty',
   'Dwelling and homeowners policies',
   'DP-1/2/3 and HO-2/3/4/6/8 forms: coverages, perils, special limits, Section II liability, and the endorsements the exam asks about.',
   40,
   array['Pick the right DP or HO form for a situation',
         'Compute HO Coverage B, C, and D limits from Coverage A',
         'Know special limits and when to schedule property',
         'Match endorsements to needs (HO 04 61, 04 90, 04 54, 04 95, 04 97)'],
   18),
  ('personal-auto-wisconsin', 'Property & Casualty',
   'Personal auto policy and Wisconsin auto law',
   'PAP Parts A through F, collision vs. other than collision, endorsements, Wisconsin minimum limits, UM/UIM rules, financial responsibility, and WAIP.',
   35,
   array['Explain each PAP part and its key exclusions',
         'Classify collision vs. other-than-collision losses',
         'State Wisconsin 25/50/10 liability and mandatory UM 25/50',
         'Describe the financial responsibility law and WAIP'],
   19),
  ('commercial-property-bop', 'Property & Casualty',
   'Commercial property, inland marine, and the BOP',
   'CPP structure, causes of loss forms, business income, key CP endorsements, inland marine, equipment breakdown, farm property, and BOP Section I.',
   40,
   array['Describe how a commercial package policy is built',
         'Apply the commercial property vacancy condition',
         'Match inland marine forms to exposures',
         'Explain BOP property features: RC, no coinsurance, 12-month business income'],
   20),
  ('casualty-liability-commercial', 'Property & Casualty',
   'Liability fundamentals, CGL, crime, and commercial auto',
   'Negligence and damages, liability limits, CGL Coverages A/B/C, occurrence vs. claims-made, commercial crime, BOP liability, and business auto symbols.',
   40,
   array['State the elements of negligence and common defenses',
         'Distinguish CGL Coverages A, B, and C',
         'Explain claims-made retro dates and extended reporting periods',
         'Use business auto covered auto symbols'],
   21),
  ('workers-comp-umbrella-surety', 'Property & Casualty',
   'Worker''s compensation, umbrella, specialty liability, and surety',
   'Wisconsin WC requirements, the WC/EL policy, premium rating, umbrella and excess liability, specialty liability lines, and surety bonds.',
   35,
   array['Know which Wisconsin employers must carry WC',
         'Explain Parts One through Three of the WC/EL policy',
         'Describe how umbrellas drop down and require underlying limits',
         'Identify the three parties to a surety bond'],
   22),
  ('flood-other-personal-coverages', 'Property & Casualty',
   'Flood, earthquake, boats, and other personal coverages',
   'The NFIP, earthquake coverage, boatowners, manufactured homes, personal umbrella, and Wisconsin''s property residual market.',
   25,
   array['State NFIP limits, waiting period, and flood definition',
         'Explain how earthquake and watercraft gaps are filled',
         'Describe WIP eligibility and ACV settlement'],
   23)
on conflict (id) do nothing;
